=== xudongliu23/PLPTreeXMLParser/src/cicp_plptree_xml_parser.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
>

	<xs:element name="child" type="child_t"/>

  <xs:complexType name="child_t">
    <xs:sequence>
			<xs:element name="attribute" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="preference" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="child" type="child_t" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== xudongliu23/PLPTreeXMLParser/cicp.xml
<?xml version="1.0" encoding="UTF-8"?>

<child xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="cicp_plptree_xml_parser.xsd">
	<attribute>BodyType</attribute>
	<preference>v:s</preference>
	<preference>s:r</preference>
	<child>
		<attribute>Make</attribute>
		<preference>h:f</preference>
		<child><!-- --></child>
		<child>
			<attribute>Price</attribute>
			<preference>l:d</preference>
			<preference>d:g</preference>
			<child><!-- --></child>
			<child><!-- --></child>
			<child><!-- --></child>
		</child>
	</child>
	<child>
		<attribute>Price</attribute>
		<preference>d:l</preference>
		<preference>l:g</preference>
		<child><!-- --></child>
		<child><!-- --></child>
		<child><!-- --></child>
	</child>
	<child>
		<attribute>Transmission</attribute>
		<preference>m:a</preference>
		<child><!-- --></child>
		<child><!-- --></child>
	</child>
</child>

=== xudongliu23/PLPTreeXMLParser/examples/cicp_plptree.xml
<?xml version="1.0" encoding="UTF-8"?>
<child xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../src/cicp_plptree_xml_parser.xsd">
	<attribute>Safety</attribute>
	<preference>med:high</preference>
	<preference>high:low</preference>
	<child>
		<attribute>MaintPrice</attribute>
		<preference>low:high</preference>
		<preference>high:med</preference>
		<preference>med:vhigh</preference>
		<child>
			<!-- -->
		</child>
		<child>
			<!-- -->
		</child>
		<child>
			<!-- -->
		</child>
		<child>
			<!-- -->
		</child>
	</child>
	<child>
		<attribute>Doors</attribute>
		<preference>2:5more</preference>
		<preference>5more:4</preference>
		<preference>4:3</preference>
		<child>
			<!-- -->
		</child>
		<child>
			<!-- -->
		</child>
		<child>
			<!-- -->
		</child>
		<child>
			<!-- -->
		</child>
	</child>
	<child>
		<!-- -->
	</child>
</child>
